### ISSUE TITLE
Doesn't show graph.

### ISSUE THREAD

**Issue by ike-9** [sdetweil/MyCovid19#14]
Hello,
I installed the module today and it showed no graph.
If I turned debug on, it showed error messages below.

[12.01.2021 16:57.04.784] [LOG]   processing response error=null response.code=200 file=modules/MyCovid19/countries-rawdata-01-12-2021.csv
[12.01.2021 16:57.04.919] [ERROR] Whoops! There was an uncaught exception...
[12.01.2021 16:57.04.952] [ERROR] TypeError: Cannot read property 'id' of undefined
    at /home/pi/Documents/MagicMirror/modules/MyCovid19/node_helper.js:372:49
    at fs.js:1245:7
    at FSReqCallback.oncomplete (fs.js:146:23)
[12.01.2021 16:57.04.961] [ERROR] MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
[12.01.2021 16:57.04.963] [ERROR] If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues

My current config is below:
![image](https://user-images.githubusercontent.com/29009351/104379673-cd1fca00-54f7-11eb-8355-07ca0280fc04.png)

Did I miss anything?

**Comment by sdetweil** [comment]
I don't see anything. I am in hospital with covid. 
no idea when I will be back. sorry

**Comment by ike-9** [comment]
Thank you very much for the response even though you are in that situation.
Please take care of yourself and hope you are back soon.

**Comment by humdinger44** [comment]
Sorry to hear that Sam! I just wanted to reach out and say that I've really
enjoyed this module and have been really impressed with your commitment to
technical support. Hope you get well soon.

**Comment by alexandruchitic** [comment]
Get well Sam, hope you'll be alright. I really enjoy your module and thank you for the support.

**Comment by sdetweil** [comment]
i don't know why the graph didn't show, but the error in debug mode is now fixed..

**Comment by sdetweil** [comment]
I am home, and feeling better.. still a ways to go..

**Comment by sdetweil** [comment]
@ike-9 can u try this again.. thx

**Comment by sdetweil** [comment]
closing, no update.. if still a problem, please reopen
